=== John-Chan/sipXtapi/sipXconfig/profilegenerator/meta/devicedefs/devicedefinition.dtd
<!ELEMENT device_definition (core_software_types+,device_type)>

<!ELEMENT core_software_types (core_software+)>

<!ELEMENT core_software ( description, version,name, core_software_profile+ )>

<!ELEMENT description (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT core_software_profile (	profile_file_name,
									profile_renderer_class?,
									profile_renderer_stylesheet?,
									profile_projection_class)>

<!ATTLIST core_software_profile
			type (phone | user | application-config | application-ref ) #REQUIRED
>

<!ELEMENT profile_file_name (#PCDATA)>
<!ELEMENT profile_renderer_class (#PCDATA)>
<!ELEMENT profile_projection_class (#PCDATA)>
<!ELEMENT profile_renderer_stylesheet (#PCDATA)>

<!ELEMENT device_type ( model, manufacturer, profile+ )>

<!ELEMENT model (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>

<!ELEMENT profile (ref_property*)>

<!ATTLIST profile
			type (phone | user | application-config | application-ref ) #REQUIRED
>

<!ELEMENT ref_property ( definition )>

<!ATTLIST ref_property
			code ID #REQUIRED
>


<!ELEMENT ref_property_group_name (#PCDATA)>

<!ELEMENT definition ( value+ )>

<!ATTLIST definition
			name CDATA #REQUIRED
			mobility ( true | false ) #REQUIRED
			cardinality ( 1..N| 0..1| 0..N| 1 | A ) #REQUIRED
			blank_entries CDATA #IMPLIED
			description CDATA #IMPLIED
>

<!ELEMENT value ( ( default_value?, max_value?, min_value? ) | ( default_value?, enum_value+ )  | ( value+) )>

<!ATTLIST value
			name CDATA #REQUIRED
			type ( string | integer | float | enumeration | container | digest | password | area ) #REQUIRED
			cardinality ( 1..N| 0..1| 0..N| 1 ) #REQUIRED			
			visibility ( read | write | hidden ) #REQUIRED
			blank_entries CDATA #IMPLIED
			read_only_value CDATA #IMPLIED
			index ( true ) #IMPLIED
			sort (	alphanum-caseinsensitive-asc | 
					alphanum-casesensitive-asc | 
					alphanum-caseinsensitive-des | 
					alphanum-casesensitive-des | 
					numeric-asc | 
					numeric-des ) #IMPLIED
					
			description CDATA #IMPLIED
>

<!ELEMENT default_value (#PCDATA)>
<!ELEMENT max_value (#PCDATA)>
<!ELEMENT min_value (#PCDATA)>
<!ELEMENT enum_value (#PCDATA)>

=== John-Chan/sipXtapi/sipXconfig/profilegenerator/meta/devicedefs/7940-definition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device_definition SYSTEM "devicedefinition.dtd"
    [<!ENTITY common-dev-defs SYSTEM "79xx-dev-prof-common-defs.xml">
    <!ENTITY common-user-defs SYSTEM "79xx-user-prof-common-defs.xml">] >

<!--
	All device definitions taken from:
	"Cisco SIP IP Phone Administrator Guide.   Version 4.0, August 2002"
	http://www.cisco.com/application/pdf/en/us/guest/products/ps2156/c1696/ccmigration_09186a00800c6d1c.pdf

-->

<!-- property descriptions taken from:

http://www.cisco.com/en/US/products/sw/voicesw/ps2156/products_administration_guide_chapter09186a00800d6a6d.html#wp1007555

-->

<device_definition>

    <core_software_types>

        <core_software>
            <description>version x.x</description>

            <version>4.2</version>

            <name>CiscoKernel</name>

            <core_software_profile type="phone">
                <profile_file_name>device-settings.txt</profile_file_name>

                <profile_renderer_class>com.pingtel.pds.pgs.plugins.renderer.XpressaConfig</profile_renderer_class>

                <profile_renderer_stylesheet>internal279xx.xsl</profile_renderer_stylesheet>

                <profile_projection_class>com.pingtel.pds.pgs.plugins.projection.StandardTopDown</profile_projection_class>
            </core_software_profile>

            <core_software_profile type="user">
                <profile_file_name>user-settings.txt</profile_file_name>

                <profile_renderer_class>com.pingtel.pds.pgs.plugins.renderer.XpressaConfig</profile_renderer_class>

                <profile_renderer_stylesheet>internal279xx.xsl</profile_renderer_stylesheet>

                <profile_projection_class>com.pingtel.pds.pgs.plugins.projection.StandardTopDown</profile_projection_class>
            </core_software_profile>

        </core_software>

    </core_software_types>

    <device_type>

        <model>7940</model>
        <manufacturer>Cisco</manufacturer>

        <profile type="phone">
            &common-dev-defs;
        </profile>

        <profile type="user">
            &common-user-defs;
        </profile>

    </device_type>

</device_definition>

=== John-Chan/sipXtapi/profilegenerator/meta/devicedefs/ixNT.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device_definition SYSTEM "devicedefinition.dtd"
    [<!ENTITY common-dev-defs SYSTEM "xpressa-dev-prof-common-defs.xml">
    <!ENTITY common-user-defs SYSTEM "xpressa-user-prof-common-defs.xml">
    <!ENTITY common-app-defs SYSTEM "xpressa-app-prof-common-defs.xml">] >

<device_definition>
   <core_software_types>
      <core_software>
         <description>version 2.0</description>

         <version>2.0</version>

         <name>softphone NT</name>

         <core_software_profile type="phone">
            <profile_file_name>pinger-config</profile_file_name>

            <profile_renderer_class>com.pingtel.pds.pgs.plugins.renderer.XpressaConfig</profile_renderer_class>

            <profile_renderer_stylesheet>internal2pinger.xsl</profile_renderer_stylesheet>

            <profile_projection_class>com.pingtel.pds.pgs.plugins.projection.StandardTopDown</profile_projection_class>
         </core_software_profile>

         <core_software_profile type="user">
            <profile_file_name>user-config</profile_file_name>

            <profile_renderer_class>com.pingtel.pds.pgs.plugins.renderer.XpressaConfig</profile_renderer_class>

            <profile_renderer_stylesheet>internal2pinger.xsl</profile_renderer_stylesheet>

            <profile_projection_class>com.pingtel.pds.pgs.plugins.projection.StandardTopDown</profile_projection_class>
         </core_software_profile>

         <core_software_profile type="application-ref">
            <profile_file_name>app-config</profile_file_name>

            <profile_renderer_class>com.pingtel.pds.pgs.plugins.renderer.XpressaAppConfig</profile_renderer_class>

            <profile_renderer_stylesheet>internal2appconfig.xsl</profile_renderer_stylesheet>

            <profile_projection_class>com.pingtel.pds.pgs.plugins.projection.StandardTopDown</profile_projection_class>
         </core_software_profile>
      </core_software>
   </core_software_types>

    <device_type>
        <model>ixpressa_x86_win32</model>
        <manufacturer>Pingtel</manufacturer>
        <profile type="phone">
            &common-dev-defs;
        </profile>
        <profile type="user">
            &common-user-defs;
        </profile>
        <profile type="application-ref">
            &common-app-defs;
        </profile>
    </device_type>
</device_definition>
